<!DOCTYPE tiles-definitions
    [
        <!ELEMENT component-definitions (definition+)>
        <!ELEMENT tiles-definitions (definition+)>
        <!ELEMENT definition (put*, putList*)>
        <!ATTLIST definition
            name CDATA #REQUIRED
            pages CDATA #IMPLIED
            path CDATA #IMPLIED
            extends CDATA #IMPLIED
            role CDATA #IMPLIED
            template CDATA #IMPLIED
            controllerClass CDATA #IMPLIED
            controllerUrl CDATA #IMPLIED>
        <!ELEMENT put (#PCDATA)>
        <!ATTLIST put
            name CDATA #REQUIRED
            value CDATA #IMPLIED
            type (string | pages | template | definition) #IMPLIED
            content CDATA #IMPLIED
            direct (true | false) #IMPLIED>
        <!ELEMENT putList ( (add* | item* | bean* | putList*)+) >
        <!ATTLIST putList
            name CDATA #REQUIRED>
        <!ELEMENT putListElements (add | item | bean)>
        <!ELEMENT add (#PCDATA)>
        <!ATTLIST add
            value CDATA #IMPLIED
            type (string | pages | template | definition) #IMPLIED
            content CDATA #IMPLIED
            direct (true | false) #IMPLIED>
        <!ELEMENT bean (#PCDATA)>
        <!ATTLIST bean
            classtype CDATA #REQUIRED>
        <!ELEMENT item (#PCDATA)>
        <!ATTLIST item
            value CDATA #REQUIRED
            link CDATA #REQUIRED
            classtype CDATA #IMPLIED
            icon CDATA #IMPLIED
            tooltip CDATA #IMPLIED>
    ]>

<tiles-definitions>
    <definition name="/run/dataexchange/regSystem.tiles" extends="layout.busitemplate">
        <put name="body" value="/pages/run/dataexchange/regSystem.jsp"/>
    </definition>
    <definition name="/run/dataexchange/systemEdit.tiles" extends="layout.busitemplateSelf">
        <put name="body" value="/pages/run/dataexchange/systemEdit.jsp"/>
    </definition>
    <definition name="/run/dataexchange/regProduct.tiles" extends="layout.busitemplate">
        <put name="body" value="/pages/run/dataexchange/regProduct.jsp"/>
    </definition>
    <definition name="/run/dataexchange/productEdit.tiles" extends="layout.busitemplateSelf">
        <put name="body" value="/pages/run/dataexchange/productEdit.jsp"/>
    </definition>
    <definition name="/run/dataexchange/sendList.tiles" extends="layout.busitemplateSelf">
        <put name="body" value="/pages/run/dataexchange/sendList.jsp"/>
    </definition>
    <definition name="/run/dataexchange/selProduct.tiles" extends="layout.busitemplateSelf">
        <put name="body" value="/pages/run/dataexchange/selProduct.jsp"/>
    </definition>
    <definition name="/run/dataexchange/receivList.tiles" extends="layout.busitemplateSelf">
        <put name="body" value="/pages/run/dataexchange/receivList.jsp"/>
    </definition>
    <definition name="/run/dataexchange/selSendProduct.tiles" extends="layout.busitemplateSelf">
        <put name="body" value="/pages/run/dataexchange/selSendProduct.jsp"/>
    </definition>
    <definition name="/run/dataexchange/monitor.tiles" extends="layout.busitemplate">
        <put name="body" value="/pages/run/dataexchange/monitor.jsp"/>
    </definition>
     <definition name="/run/dataexchange/login.tiles" extends="layout.busitemplateLogin" >
       <put name="body" value="/pages/run/dataexchange/login.jsp" />
   </definition>
   <definition name="/run/dataexchange/main.tiles" extends="layout.busitemplate">
        <put name="body" value="/pages/run/dataexchange/main.jsp"/>
    </definition>
    <definition name="/run/dataexchange/uploadProduct.tiles" extends="layout.busitemplateSelf">
        <put name="body" value="/pages/run/dataexchange/uploadProduct.jsp"/>
    </definition>
</tiles-definitions>
