<!DOCTYPE tiles-definitions
    [
        <!ELEMENT component-definitions (definition+)>
        <!ELEMENT tiles-definitions (definition+)>
        <!ELEMENT definition (put*, putList*)>
        <!ATTLIST definition
            name CDATA #REQUIRED
            pages CDATA #IMPLIED
            path CDATA #IMPLIED
            extends CDATA #IMPLIED
            role CDATA #IMPLIED
            template CDATA #IMPLIED
            controllerClass CDATA #IMPLIED
            controllerUrl CDATA #IMPLIED>
        <!ELEMENT put (#PCDATA)>
        <!ATTLIST put
            name CDATA #REQUIRED
            value CDATA #IMPLIED
            type (string | pages | template | definition) #IMPLIED
            content CDATA #IMPLIED
            direct (true | false) #IMPLIED>
        <!ELEMENT putList ( (add* | item* | bean* | putList*)+) >
        <!ATTLIST putList
            name CDATA #REQUIRED>
        <!ELEMENT putListElements (add | item | bean)>
        <!ELEMENT add (#PCDATA)>
        <!ATTLIST add
            value CDATA #IMPLIED
            type (string | pages | template | definition) #IMPLIED
            content CDATA #IMPLIED
            direct (true | false) #IMPLIED>
        <!ELEMENT bean (#PCDATA)>
        <!ATTLIST bean
            classtype CDATA #REQUIRED>
        <!ELEMENT item (#PCDATA)>
        <!ATTLIST item
            value CDATA #REQUIRED
            link CDATA #REQUIRED
            classtype CDATA #IMPLIED
            icon CDATA #IMPLIED
            tooltip CDATA #IMPLIED>
    ]>
<tiles-definitions>
    <definition name="/self/JXKHSelf.tiles" extends="layout.busitemplate" >
            <put name="body" value="/pages/self/JXKHSelf.jsp" />
    </definition>
    <definition name="/self/VideoNewsList.tiles" extends="layout.busitemplate" >
            <put name="body" value="/pages/self/VideoNewsList.jsp" />
    </definition>

    <definition name="/self/PostBookQuery.tiles" extends="layout.busitemplate" >
            <put name="body" value="/pages/self/info/PostBookQuery.jsp" />
    </definition>
    <definition name="/self/DeptBookQuery.tiles" extends="layout.busitemplate" >
            <put name="body" value="/pages/self/info/DeptBookQuery.jsp" />
    </definition>

    <definition name="/self/info/ChkList.tiles" extends="layout.busitemplateSelf" >
            <put name="body" value="/pages/self/info/ChkList.jsp" />
    </definition>
    <definition name="/self/info/ChkInsertList.tiles" extends="layout.busitemplateSelf" >
            <put name="body" value="/pages/self/info/ChkInsertList.jsp" />
    </definition>
    <definition name="/self/info/InsertInfo.tiles" extends="layout.busitemplateSelf" >
        <put name="body" value="/pages/self/info/InsertInfo.jsp" />
    </definition>
    <definition name="/self/info/BatchModifyInfo.tiles" extends="layout.busitemplateSelf" >
        <put name="body" value="/pages/self/info/BatchModifyInfo.jsp" />
    </definition>
    <definition name="/self/info/ModifyInfo.tiles" extends="layout.busitemplateSelf" >
        <put name="body" value="/pages/self/info/ModifyInfo.jsp" />
    </definition>

    <definition name="/self/info/PersonEditInfo.tiles" extends="layout.busitemplateLogin" >
        <put name="body" value="/pages/self/info/PersonEditInfo.jsp" />
    </definition>
    <definition name="/self/wage/taxCountMethod.tiles" extends="layout.busitemplate" >
        <put name="body" value="/pages/self/wage/taxCountMethod.jsp" />
    </definition>
    <definition name="/self/wage/medicalPayoff.tiles" extends="layout.busitemplate" >
        <put name="body" value="/pages/self/wage/medicalPayoff.jsp" />
    </definition>
    <definition name="/self/PersonInfoList.tiles" extends="layout.busitemplateSelf" >
        <put name="body" value="/pages/self/PersonInfoList.jsp" />
    </definition>
    <definition name="/self/PersonInfoListChild.tiles" extends="layout.busitemplate" >
        <put name="body" value="/pages/self/PersonInfoListChild.jsp" />
    </definition>
    <definition name="/self/SelfInfo.tiles" extends="layout.busitemplate" >
        <put name="body" value="/pages/self/SelfInfo.jsp" />
    </definition>
    <definition name="/self/SelfInfo2.tiles" extends="layout.busitemplate" >
        <put name="body" value="/pages/self/SelfInfo2.jsp" />
    </definition>
    <definition name="/self/SelfMain.tiles" extends="layout.busitemplateLogin">
        <put name="body" value="/pages/self/SelfMain.jsp"/>
    </definition>
    <definition name="/self/SelfMain2.tiles" extends="layout.busitemplateLogin">
        <put name="body" value="/pages/self/SelfMain2.jsp"/>
    </definition>

    <definition name="/self/QueryOneBulletin.tiles" extends="layout.busitemplate">
        <put name="body" value="/pages/self/QueryOneBulletin.jsp"/>
    </definition>
    <definition name="/self/QueryOneNews.tiles" extends="layout.busitemplate">
        <put name="body" value="/pages/self/QueryOneNews.jsp"/>
    </definition>
    <definition name="/self/PayQuerySum.tiles" extends="layout.busitemplate" >
        <put name="body" value="/pages/self/PayQuerySum.jsp" />
    </definition>
    <definition name="/self/TaxQuerySum.tiles" extends="layout.busitemplate" >
        <put name="body" value="/pages/self/TaxQuerySum.jsp" />
    </definition>
    <definition name="/self/PayQueryByMonth.tiles" extends="layout.busitemplate" >
        <put name="body" value="/pages/self/PayQueryByMonth.jsp" />
    </definition>
    <definition name="/self/PayQueryPrint.tiles" extends="layout.busitemplate" >
        <put name="body" value="/pages/self/PayQueryPrint.jsp" />
    </definition>
    <definition name="/self/BakQuery.tiles" extends="layout.busitemplate" >
        <put name="body" value="/pages/self/BakQuery.jsp" />
    </definition>
    <definition name="/self/BakUpdate.tiles" extends="layout.busitemplate" >
        <put name="body" value="/pages/self/BakUpdate.jsp" />
    </definition>
    <definition name="/self/ContractTextQuery.tiles" extends="layout.busitemplate" >
      <put name="body" value="/pages/self/ContractTextQuery.jsp" />
  </definition>

    <definition name="/self/info/PersonInfoDetail.tiles" extends="layout.busitemplateLogin" >
        <put name="body" value="/pages/self/info/PersonInfoDetail.jsp" />
    </definition>
      <definition name="/self/info/PersonInfoDetailList.tiles" extends="layout.busitemplateLogin" >
        <put name="body" value="/pages/self/info/PersonInfoDetailList.jsp" />
    </definition>    

    <definition name="/self/ManpowerCostQuery.tiles" extends="layout.busitemplate" >
        <put name="body" value="/pages/self/ManpowerCostQuery.jsp" />
    </definition>

    <definition name="/self/ShowStars.tiles" extends="layout.busitemplateLogin" >
        <put name="body" value="/pages/self/ShowStars.jsp" />
    </definition>
    <definition name="/self/ShowAddress.tiles" extends="layout.busitemplateLogin" >
        <put name="body" value="/pages/self/ShowAddress.jsp" />
    </definition>
    <definition name="/self/ShowSurvey.tiles" extends="layout.busitemplateLogin" >
        <put name="body" value="/pages/self/ShowSurvey.jsp" />
    </definition>

    <definition name="/self/StarsList.tiles" extends="layout.busitemplate" >
        <put name="body" value="/pages/self/StarsList.jsp" />
    </definition>

    <definition name="/self/AddressList.tiles" extends="layout.busitemplateSelf" >
        <put name="body" value="/pages/self/AddressList.jsp" />
    </definition>

</tiles-definitions>
